// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhaVeHVSoQJkAWEo14dT_nITdQ2wOxG9g',
    appId: '1:490539529973:web:3fb0d3b03cfe719043f7bc',
    messagingSenderId: '490539529973',
    projectId: 'watertrack-dded0',
    authDomain: 'watertrack-dded0.firebaseapp.com',
    databaseURL: 'https://watertrack-dded0.firebaseio.com',
    storageBucket: 'watertrack-dded0.appspot.com',
    measurementId: 'G-V2SYKW6P2Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLvWJLgwHKHEfrap9_uhSEjKXNa1Ymvxg',
    appId: '1:490539529973:android:b4079c2f0e0489fe43f7bc',
    messagingSenderId: '490539529973',
    projectId: 'watertrack-dded0',
    databaseURL: 'https://watertrack-dded0.firebaseio.com',
    storageBucket: 'watertrack-dded0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiIRq47FT5U5dfEAPDsYOvOxlYDi9oERs',
    appId: '1-490539529973-ios-013cad5b6755b6df43f7bc',
    messagingSenderId: '490539529973',
    projectId: 'watertrack-dded0',
    databaseURL: 'https://watertrack-dded0.firebaseio.com',
    storageBucket: 'watertrack-dded0.appspot.com',
    androidClientId: '490539529973-8gba1idnn93rmn6slhn2f7acab88qq7b.apps.googleusercontent.com',
    iosClientId: '490539529973-g0q6f3ht3lqdhkaro04t416gde25uvjt.apps.googleusercontent.com',
    iosBundleId: 'com.svindland.watertrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiIRq47FT5U5dfEAPDsYOvOxlYDi9oERs',
    appId: '1-490539529973-ios-013cad5b6755b6df43f7bc',
    messagingSenderId: '490539529973',
    projectId: 'watertrack-dded0',
    databaseURL: 'https://watertrack-dded0.firebaseio.com',
    storageBucket: 'watertrack-dded0.appspot.com',
    androidClientId: '490539529973-8gba1idnn93rmn6slhn2f7acab88qq7b.apps.googleusercontent.com',
    iosClientId: '490539529973-g0q6f3ht3lqdhkaro04t416gde25uvjt.apps.googleusercontent.com',
    iosBundleId: 'com.svindland.watertrack',
  );
}
